### ISSUE TITLE
For long running request

### ISSUE THREAD

**Issue by gioa44** [altasoft/mvc-navigation#3]
როდესაც request-ს მოუნდება ცოტა დიდ ხანს გამოვუტანოთ 'waiting response popup'-ი შესაბამისი ტექსტით, თუ ლოდინის დრო გადააჭარბებს მოთმენად მაქსიმუმს მაგ. 5 წამს შევცვალოთ ტექსტი რაღაც ამდაგვარით: 'response takes more time than expected'

**Comment by playerx** [comment]
მრავალენიანობის გამო ტექსტი შევცვალეთ მოძრავი იკონკით
